site_name: VIVO Project Documentation
site_description: This document is part of the vivo project documentation
site_author: Florian Kotschka,  Rolf Guescini
docs_dir: docs/
repo_name: BUA-VIVO/projektdokumentation
repo_url: https://github.com/BUA-VIVO/projektdokumentation
nav:
  - Home: index.md
  - Technische Dokumentation:
    - OpenStack und Server: OpenStackServers.md
    - Servers:
      - Vivo-Server: vivo.md
      - Solr-Server: solrserver.md
      - Mongo-Server: mongoserver.md
      - Testserver: testserver.md
      - Kairntech: kairntech.md
    - Pipelines:
      - Cluster-scripte: clusters.md
      - Mongo-import: mongoimport.md    
      - Mongo2Vivo: pipelines.md
      - Classification pipelines:
        - Automatic pre classification: vorklassifikationspipelines.md
        - API-import: apiimport.md
        - API-classification: api-klassifikationspipelines.md
  - Ontologies:
    - Overview: ontologien.md
    - BUA VIVO Upper Ontology: bua-ontology.md
    - Alliance member Ontologies:
      - Organigram ontologies: organigram.md
      - Charité – Universitätsmedizin Berlin Ontology Extension: charite-ontology.md
      - Freie Universität Berlin Ontology Extension: fub-ontology.md
      - Humbold Universität zu Berlin Ontology Extension: hub-ontology.md
      - Technische Universität Berlin Ontology Extension: tub-ontology.md
  - Vokabularies: vokabularen.md
theme:
  name: material
  language: en
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: blue grey
      accent: light blue 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: blue grey
      accent: cyan

  markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:mkdocs.material.extensions.emoji.twemoji
      emoji_generator: !!python/name:mkdocs.material.extensions.emoji.to_svg



copyright: |
  &copy; 2023 <a href="https://github.com/guescinr" target="_blank" rel="noopener">Rolf Guescini</a> <a href="https://github.com/fkotschka"  target="_blank" rel="noopener">Florian Kotschka</a> 