site_name: VIVO Project Documentation
site_description: This document is part of the vivo project documentation
site_author: Florian Kotschka,  Rolf Guescini
docs_dir: docs/
repo_name: BUA-VIVO/projektdokumentation
repo_url: https://github.com/BUA-VIVO/projektdokumentation
nav:
  - index: index.md
  - test: test.md
  - OpenStack und Server: OpenStackServer.md
theme:
  name: material
