site_name: VIVO Project Documentation
site_description: This document is part of the vivo project documentation
site_author: Florian Kotschka,  Rolf Guescini
docs_dir: docs/
repo_name: BUA-VIVO/projektdokumentation
repo_url: https://github.com/BUA-VIVO/projektdokumentation
nav:
  - Home: index.md
  - Technische Dokumentation:
    - OpenStack und Server: OpenStackServers.md
    - VIVO: vivo.md
    - Servers:
      - Vivo-Server: vivoserver.md
      - Solr-Server: solrserver.md
      - Mongo-Server: mongoserver.md
      - Testserver: testserver.md
      - Kairntech: kairntech.md
    - Pipelines:
      - Cluster-scripte: clusters.md
      - Mongo-import: mongoimport.md    
      - Mongo2Vivo: pipelines.md
      - Klassifikationspipelines:
        - Automatische vorklassifikation: vorklassifikationspipelines.md
        - API-import: apiimport.md
        - API-klassifikation: api-klassifikationspipelines.md
  - Ontologien: ontologien.md
  - Vokabularen: vokabularen.md
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: teal
      accent: purple 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: teal
      accent: lime