site_name: VIVO Project Documentation
site_description: This document is part of the vivo project documentation
site_author: Florian Kotschka,  Rolf Guescini
docs_dir: docs/
repo_name: BUA-VIVO/projektdokumentation
repo_url: https://github.com/BUA-VIVO/projektdokumentation
nav:
  - Home: index.md
  - Technische Dokumentation:
    - OpenStack und Server: OpenStackServers.md
    - VIVO: vivo.md
    - Servers:
      - Vivo-Server: vivoserver.md
      - Solr-Server: solrserver.md
      - Mongo-Server: mongoserver.md
      - Testserver: testserver.md
      - Kairntech: kairntech.md
    - Pipelines:    
      - VIVO-pipelines: pipelines.md
      - Klassifikationspipelines: pipelines.md
  - Ontologien: ontologien.md
  - Vokabularen: vokabularen.md
theme:
  name: readthedocs
  highlightjs: true
  hljs_languages:
    - yaml
    - python
    - java
    - owl
    - rdf
    - ttl
  nav_style: dark
